export const CREATE_TICKET = 'CREATE_TICKET';
export const FETCH_TICKETS = 'FETCH_TICKETS';
export const FETCH_TICKET = 'FETCH_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const EDIT_TICKET = 'EDIT_TICKET';